name: Cleanup GHCR Container Images

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "30 1 * * *"  # Runs daily at 01:30 UTC

jobs:
  cleanup-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required to delete images

    steps:
      - name: Clean up Container Images in GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: packages
          keep-n-tagged: 10
          exclude-tags: v.*,latest
          delete-untagged: true
          use-regex: true
